version: '3'
services:
  mongo:
    image: library/mongo:4.2-bionic
    container_name: 'app03-mongo'
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
# uncomment this if your want your mongo data be persisted on your local machine
# rather than thrown away every time the container restarts
#   volumes:
#     - ./mongo/data:/data/db
    ports:
      - 27017-27019:27017-27019
